
// This file has been generated by the GUI designer. Do not modify.
namespace Artikli
{
	public partial class MainWindow
	{
		private global::Gtk.VBox vbox4;

		private global::Gtk.ScrolledWindow GtkScrolledWindow;

		private global::Gtk.NodeView popisArtikala;

		private global::Gtk.HBox hbox1;

		private global::Gtk.Label label6;

		private global::Gtk.Label labelRedak;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget Artikli.MainWindow
			this.Name = "Artikli.MainWindow";
			this.Title = global::Mono.Unix.Catalog.GetString("Naručivanje");
			this.WindowPosition = ((global::Gtk.WindowPosition)(3));
			// Container child Artikli.MainWindow.Gtk.Container+ContainerChild
			this.vbox4 = new global::Gtk.VBox();
			this.vbox4.Name = "vbox4";
			this.vbox4.Spacing = 6;
			// Container child vbox4.Gtk.Box+BoxChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow();
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			this.popisArtikala = new global::Gtk.NodeView();
			this.popisArtikala.CanFocus = true;
			this.popisArtikala.Name = "popisArtikala";
			this.GtkScrolledWindow.Add(this.popisArtikala);
			this.vbox4.Add(this.GtkScrolledWindow);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox4[this.GtkScrolledWindow]));
			w2.Position = 0;
			// Container child vbox4.Gtk.Box+BoxChild
			this.hbox1 = new global::Gtk.HBox();
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = 6;
			// Container child hbox1.Gtk.Box+BoxChild
			this.label6 = new global::Gtk.Label();
			this.label6.Name = "label6";
			this.label6.LabelProp = global::Mono.Unix.Catalog.GetString("Trenutno označeni artikl:");
			this.hbox1.Add(this.label6);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.label6]));
			w3.Position = 0;
			w3.Expand = false;
			w3.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.labelRedak = new global::Gtk.Label();
			this.labelRedak.Name = "labelRedak";
			this.hbox1.Add(this.labelRedak);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.labelRedak]));
			w4.Position = 1;
			w4.Expand = false;
			w4.Fill = false;
			this.vbox4.Add(this.hbox1);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vbox4[this.hbox1]));
			w5.Position = 1;
			w5.Expand = false;
			w5.Fill = false;
			this.Add(this.vbox4);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.DefaultWidth = 400;
			this.DefaultHeight = 300;
			this.Show();
			this.DeleteEvent += new global::Gtk.DeleteEventHandler(this.OnDeleteEvent);
		}
	}
}
