
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.Alignment alignment1;

	private global::Gtk.Table table1;

	private global::Gtk.Button buttonInfo;

	private global::Gtk.Button buttonInfo1;

	private global::Gtk.Button buttonQuestion;

	private global::Gtk.Button buttonQuestion1;

	private global::Gtk.Button buttonWarning;

	private global::Gtk.Label label1;

	private global::Gtk.Label label3;

	private global::Gtk.Label lOdgovor1;

	private global::Gtk.Label lOdgovor2;

	protected virtual void Build()
	{
		global::Stetic.Gui.Initialize(this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString("Prikaz dijaloga");
		this.WindowPosition = ((global::Gtk.WindowPosition)(1));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.alignment1 = new global::Gtk.Alignment(1F, 0.5F, 1F, 1F);
		this.alignment1.Name = "alignment1";
		this.alignment1.BorderWidth = ((uint)(20));
		// Container child alignment1.Gtk.Container+ContainerChild
		this.table1 = new global::Gtk.Table(((uint)(5)), ((uint)(3)), false);
		this.table1.Name = "table1";
		this.table1.RowSpacing = ((uint)(12));
		this.table1.ColumnSpacing = ((uint)(12));
		// Container child table1.Gtk.Table+TableChild
		this.buttonInfo = new global::Gtk.Button();
		this.buttonInfo.CanFocus = true;
		this.buttonInfo.Name = "buttonInfo";
		this.buttonInfo.UseUnderline = true;
		this.buttonInfo.Label = global::Mono.Unix.Catalog.GetString("Prikaži informaciju");
		this.table1.Add(this.buttonInfo);
		global::Gtk.Table.TableChild w1 = ((global::Gtk.Table.TableChild)(this.table1[this.buttonInfo]));
		w1.TopAttach = ((uint)(2));
		w1.BottomAttach = ((uint)(3));
		w1.XOptions = ((global::Gtk.AttachOptions)(4));
		w1.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.buttonInfo1 = new global::Gtk.Button();
		this.buttonInfo1.CanFocus = true;
		this.buttonInfo1.Name = "buttonInfo1";
		this.buttonInfo1.UseUnderline = true;
		this.buttonInfo1.Label = global::Mono.Unix.Catalog.GetString("Prikaži grešku");
		this.table1.Add(this.buttonInfo1);
		global::Gtk.Table.TableChild w2 = ((global::Gtk.Table.TableChild)(this.table1[this.buttonInfo1]));
		w2.TopAttach = ((uint)(3));
		w2.BottomAttach = ((uint)(4));
		w2.XOptions = ((global::Gtk.AttachOptions)(4));
		w2.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.buttonQuestion = new global::Gtk.Button();
		this.buttonQuestion.CanFocus = true;
		this.buttonQuestion.Name = "buttonQuestion";
		this.buttonQuestion.UseUnderline = true;
		this.buttonQuestion.Label = global::Mono.Unix.Catalog.GetString("Prikaži pitanje");
		this.table1.Add(this.buttonQuestion);
		global::Gtk.Table.TableChild w3 = ((global::Gtk.Table.TableChild)(this.table1[this.buttonQuestion]));
		w3.XOptions = ((global::Gtk.AttachOptions)(4));
		w3.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.buttonQuestion1 = new global::Gtk.Button();
		this.buttonQuestion1.CanFocus = true;
		this.buttonQuestion1.Name = "buttonQuestion1";
		this.buttonQuestion1.UseUnderline = true;
		this.buttonQuestion1.Label = global::Mono.Unix.Catalog.GetString("Prikaži pitanje (2)");
		this.table1.Add(this.buttonQuestion1);
		global::Gtk.Table.TableChild w4 = ((global::Gtk.Table.TableChild)(this.table1[this.buttonQuestion1]));
		w4.TopAttach = ((uint)(4));
		w4.BottomAttach = ((uint)(5));
		w4.XOptions = ((global::Gtk.AttachOptions)(4));
		w4.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.buttonWarning = new global::Gtk.Button();
		this.buttonWarning.CanFocus = true;
		this.buttonWarning.Name = "buttonWarning";
		this.buttonWarning.UseUnderline = true;
		this.buttonWarning.Label = global::Mono.Unix.Catalog.GetString("Prikaži upozorenje");
		this.table1.Add(this.buttonWarning);
		global::Gtk.Table.TableChild w5 = ((global::Gtk.Table.TableChild)(this.table1[this.buttonWarning]));
		w5.TopAttach = ((uint)(1));
		w5.BottomAttach = ((uint)(2));
		w5.XOptions = ((global::Gtk.AttachOptions)(4));
		w5.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.label1 = new global::Gtk.Label();
		this.label1.Name = "label1";
		this.label1.Xalign = 1F;
		this.label1.LabelProp = global::Mono.Unix.Catalog.GetString("Odgovor je:");
		this.table1.Add(this.label1);
		global::Gtk.Table.TableChild w6 = ((global::Gtk.Table.TableChild)(this.table1[this.label1]));
		w6.LeftAttach = ((uint)(1));
		w6.RightAttach = ((uint)(2));
		w6.XOptions = ((global::Gtk.AttachOptions)(4));
		w6.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.label3 = new global::Gtk.Label();
		this.label3.Name = "label3";
		this.label3.Xalign = 1F;
		this.label3.LabelProp = global::Mono.Unix.Catalog.GetString("Odgovor je:");
		this.table1.Add(this.label3);
		global::Gtk.Table.TableChild w7 = ((global::Gtk.Table.TableChild)(this.table1[this.label3]));
		w7.TopAttach = ((uint)(4));
		w7.BottomAttach = ((uint)(5));
		w7.LeftAttach = ((uint)(1));
		w7.RightAttach = ((uint)(2));
		w7.XOptions = ((global::Gtk.AttachOptions)(4));
		w7.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.lOdgovor1 = new global::Gtk.Label();
		this.lOdgovor1.WidthRequest = 200;
		this.lOdgovor1.Name = "lOdgovor1";
		this.lOdgovor1.Xalign = 0F;
		this.lOdgovor1.LabelProp = global::Mono.Unix.Catalog.GetString("nema");
		this.table1.Add(this.lOdgovor1);
		global::Gtk.Table.TableChild w8 = ((global::Gtk.Table.TableChild)(this.table1[this.lOdgovor1]));
		w8.LeftAttach = ((uint)(2));
		w8.RightAttach = ((uint)(3));
		w8.XOptions = ((global::Gtk.AttachOptions)(4));
		w8.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.lOdgovor2 = new global::Gtk.Label();
		this.lOdgovor2.Name = "lOdgovor2";
		this.lOdgovor2.Xalign = 0F;
		this.lOdgovor2.LabelProp = global::Mono.Unix.Catalog.GetString("nema");
		this.table1.Add(this.lOdgovor2);
		global::Gtk.Table.TableChild w9 = ((global::Gtk.Table.TableChild)(this.table1[this.lOdgovor2]));
		w9.TopAttach = ((uint)(4));
		w9.BottomAttach = ((uint)(5));
		w9.LeftAttach = ((uint)(2));
		w9.RightAttach = ((uint)(3));
		w9.XOptions = ((global::Gtk.AttachOptions)(4));
		w9.YOptions = ((global::Gtk.AttachOptions)(4));
		this.alignment1.Add(this.table1);
		this.Add(this.alignment1);
		if ((this.Child != null))
		{
			this.Child.ShowAll();
		}
		this.DefaultWidth = 444;
		this.DefaultHeight = 248;
		this.Show();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler(this.OnDeleteEvent);
		this.buttonWarning.Clicked += new global::System.EventHandler(this.showWarning);
		this.buttonQuestion1.Clicked += new global::System.EventHandler(this.showCustomQuestion);
		this.buttonQuestion.Clicked += new global::System.EventHandler(this.showQuestion);
		this.buttonInfo1.Clicked += new global::System.EventHandler(this.showError);
		this.buttonInfo.Clicked += new global::System.EventHandler(this.showInfo);
	}
}
