
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.VBox vbox1;

	private global::Gtk.ScrolledWindow GtkScrolledWindow;

	private global::Gtk.NodeView nvNarudzbe;

	private global::Gtk.HBox hbox1;

	private global::Gtk.VBox vbox4;

	private global::Gtk.Label label1;

	private global::Gtk.Label label2;

	private global::Gtk.VBox vbox5;

	private global::Gtk.Label lBrojDokumenta;

	private global::Gtk.Label lDatum;

	private global::Gtk.VBox vbox6;

	private global::Gtk.Label label3;

	private global::Gtk.VBox vbox7;

	private global::Gtk.Label lBrojStavaka;

	private global::Gtk.ScrolledWindow GtkScrolledWindow1;

	private global::Gtk.NodeView nvStavke;

	protected virtual void Build()
	{
		global::Stetic.Gui.Initialize(this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString("Listanje narudžbi");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		this.BorderWidth = ((uint)(15));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.vbox1 = new global::Gtk.VBox();
		this.vbox1.Name = "vbox1";
		this.vbox1.Spacing = 20;
		// Container child vbox1.Gtk.Box+BoxChild
		this.GtkScrolledWindow = new global::Gtk.ScrolledWindow();
		this.GtkScrolledWindow.Name = "GtkScrolledWindow";
		this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
		this.nvNarudzbe = new global::Gtk.NodeView();
		this.nvNarudzbe.CanFocus = true;
		this.nvNarudzbe.Name = "nvNarudzbe";
		this.GtkScrolledWindow.Add(this.nvNarudzbe);
		this.vbox1.Add(this.GtkScrolledWindow);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.GtkScrolledWindow]));
		w2.Position = 0;
		// Container child vbox1.Gtk.Box+BoxChild
		this.hbox1 = new global::Gtk.HBox();
		this.hbox1.Name = "hbox1";
		this.hbox1.Spacing = 6;
		// Container child hbox1.Gtk.Box+BoxChild
		this.vbox4 = new global::Gtk.VBox();
		this.vbox4.WidthRequest = 100;
		this.vbox4.Name = "vbox4";
		this.vbox4.Spacing = 6;
		// Container child vbox4.Gtk.Box+BoxChild
		this.label1 = new global::Gtk.Label();
		this.label1.Name = "label1";
		this.label1.Xalign = 1F;
		this.label1.LabelProp = global::Mono.Unix.Catalog.GetString("Broj:");
		this.vbox4.Add(this.label1);
		global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox4[this.label1]));
		w3.Position = 0;
		w3.Expand = false;
		w3.Fill = false;
		// Container child vbox4.Gtk.Box+BoxChild
		this.label2 = new global::Gtk.Label();
		this.label2.Name = "label2";
		this.label2.Xalign = 1F;
		this.label2.LabelProp = global::Mono.Unix.Catalog.GetString("Datum:");
		this.vbox4.Add(this.label2);
		global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox4[this.label2]));
		w4.Position = 1;
		w4.Expand = false;
		w4.Fill = false;
		this.hbox1.Add(this.vbox4);
		global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.vbox4]));
		w5.Position = 0;
		w5.Expand = false;
		w5.Fill = false;
		// Container child hbox1.Gtk.Box+BoxChild
		this.vbox5 = new global::Gtk.VBox();
		this.vbox5.WidthRequest = 150;
		this.vbox5.Name = "vbox5";
		this.vbox5.Spacing = 6;
		// Container child vbox5.Gtk.Box+BoxChild
		this.lBrojDokumenta = new global::Gtk.Label();
		this.lBrojDokumenta.Name = "lBrojDokumenta";
		this.lBrojDokumenta.LabelProp = global::Mono.Unix.Catalog.GetString("label2");
		this.vbox5.Add(this.lBrojDokumenta);
		global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.vbox5[this.lBrojDokumenta]));
		w6.Position = 0;
		w6.Expand = false;
		w6.Fill = false;
		// Container child vbox5.Gtk.Box+BoxChild
		this.lDatum = new global::Gtk.Label();
		this.lDatum.Name = "lDatum";
		this.lDatum.LabelProp = global::Mono.Unix.Catalog.GetString("label3");
		this.vbox5.Add(this.lDatum);
		global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.vbox5[this.lDatum]));
		w7.Position = 1;
		w7.Expand = false;
		w7.Fill = false;
		this.hbox1.Add(this.vbox5);
		global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.vbox5]));
		w8.Position = 1;
		w8.Expand = false;
		w8.Fill = false;
		// Container child hbox1.Gtk.Box+BoxChild
		this.vbox6 = new global::Gtk.VBox();
		this.vbox6.WidthRequest = 100;
		this.vbox6.Name = "vbox6";
		this.vbox6.Spacing = 6;
		// Container child vbox6.Gtk.Box+BoxChild
		this.label3 = new global::Gtk.Label();
		this.label3.Name = "label3";
		this.label3.Xalign = 1F;
		this.label3.LabelProp = global::Mono.Unix.Catalog.GetString("Broj stavaka:");
		this.vbox6.Add(this.label3);
		global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.vbox6[this.label3]));
		w9.Position = 0;
		w9.Expand = false;
		w9.Fill = false;
		this.hbox1.Add(this.vbox6);
		global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.vbox6]));
		w10.Position = 2;
		w10.Expand = false;
		w10.Fill = false;
		// Container child hbox1.Gtk.Box+BoxChild
		this.vbox7 = new global::Gtk.VBox();
		this.vbox7.WidthRequest = 150;
		this.vbox7.Name = "vbox7";
		this.vbox7.Spacing = 6;
		// Container child vbox7.Gtk.Box+BoxChild
		this.lBrojStavaka = new global::Gtk.Label();
		this.lBrojStavaka.Name = "lBrojStavaka";
		this.lBrojStavaka.LabelProp = global::Mono.Unix.Catalog.GetString("label2");
		this.vbox7.Add(this.lBrojStavaka);
		global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.vbox7[this.lBrojStavaka]));
		w11.Position = 0;
		w11.Expand = false;
		w11.Fill = false;
		this.hbox1.Add(this.vbox7);
		global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.vbox7]));
		w12.Position = 3;
		w12.Expand = false;
		w12.Fill = false;
		this.vbox1.Add(this.hbox1);
		global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.hbox1]));
		w13.Position = 1;
		w13.Expand = false;
		w13.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.GtkScrolledWindow1 = new global::Gtk.ScrolledWindow();
		this.GtkScrolledWindow1.Name = "GtkScrolledWindow1";
		this.GtkScrolledWindow1.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow1.Gtk.Container+ContainerChild
		this.nvStavke = new global::Gtk.NodeView();
		this.nvStavke.CanFocus = true;
		this.nvStavke.Name = "nvStavke";
		this.GtkScrolledWindow1.Add(this.nvStavke);
		this.vbox1.Add(this.GtkScrolledWindow1);
		global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.GtkScrolledWindow1]));
		w15.Position = 2;
		this.Add(this.vbox1);
		if ((this.Child != null))
		{
			this.Child.ShowAll();
		}
		this.DefaultWidth = 752;
		this.DefaultHeight = 412;
		this.Show();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler(this.OnDeleteEvent);
	}
}
